import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#5C51F0',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  statusBarContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  timeText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 16,
    fontWeight: '600',
  },
  statusIcons: {
    flexDirection: 'row',
    gap: 4,
  },
  statusIcon: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
  },
  headerContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    position: 'relative',
    gap: 12,
  },
  headerLeftSection: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerLeftIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerLeftIconText: {
    fontSize: 18,
  },
  headerLeftContent: {
    flex: 1,
  },
  headerItem: {
    flex: 1,
  },
  headerNumber: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 28,
    fontWeight: '600',
  },
  headerHighlight: {
    color: '#FF9500',
    fontSize: 28,
    fontWeight: '700',
  },
  headerLabel: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  waterButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  waterIcon: {
    fontSize: 22,
  },
  chartContainer: {
    width: '100%',
    paddingHorizontal: 15,
    paddingVertical: 30,
    alignItems: 'center',
    flexDirection: 'row',
  },
  chartAxisLabels: {
    flexDirection: 'column-reverse',
    justifyContent: 'space-around',
    height: 180,
    marginRight: 8,
  },
  axisLabel: {
    fontSize: 10,
    color: 'rgba(255, 255, 255, 0.5)',
    fontWeight: '500',
    width: 30,
    textAlign: 'right',
  },
  chartContent: {
    flex: 1,
    height: 180,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
  },
  barWrapper: {
    alignItems: 'center',
    flex: 1,
    marginHorizontal: 5,
  },
  bar: {
    width: '100%',
    backgroundColor: 'rgba(200, 190, 255, 0.5)',
    borderRadius: 12,
    minHeight: 20,
  },
  dayLabel: {
    marginTop: 10,
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.6)',
  },
  card: {
    width: SCREEN_WIDTH - 40,
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 10,
    marginBottom: 20,
  },
  cardHeaderRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  cardLogo: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardLogoText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
  segmentedControl: {
    flexDirection: 'row',
    backgroundColor: '#F0F0F0',
    borderRadius: 12,
    padding: 4,
    gap: 4,
  },
  segmentButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: 'transparent',
  },
  segmentButtonActive: {
    backgroundColor: '#5C51F0',
  },
  segmentText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#666',
  },
  segmentTextActive: {
    color: '#FFF',
  },
  stepsNumber: {
    fontSize: 72,
    fontWeight: '800',
    color: '#000',
    marginVertical: 8,
    lineHeight: 80,
  },
  stepsLabel: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
    marginBottom: 28,
  },
  progressBar: {
    height: 4,
    backgroundColor: '#5C51F0',
    borderRadius: 2,
    marginBottom: 28,
    minHeight: 4,
  },
  metricsContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 28,
    paddingBottom: 28,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  metric: {
    alignItems: 'center',
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#000',
  },
  metricLabel: {
    fontSize: 12,
    color: '#999',
    marginTop: 6,
    fontWeight: '500',
  },
  metricUnit: {
    fontSize: 10,
    color: '#CCC',
    marginTop: 2,
  },
  controls: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: 12,
  },
  controlButton: {
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: '#F5F5F5',
    minWidth: 70,
  },
  controlButtonActive: {
    backgroundColor: '#5C51F0',
  },
  controlIcon: {
    fontSize: 24,
  },
  controlLabel: {
    fontSize: 12,
    color: '#333',
    marginTop: 6,
    fontWeight: '600',
  },
  controlLabelActive: {
    color: '#FFF',
  },
  cardHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerLogo: {
    fontSize: 32,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
  },
  periodSelector: {
    flexDirection: 'row',
    backgroundColor: '#F0F0F0',
    borderRadius: 8,
    padding: 3,
    gap: 2,
  },
  periodButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  periodButtonActive: {
    backgroundColor: '#5C51F0',
  },
  periodText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
  },
  periodTextActive: {
    color: '#FFF',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  waterIconButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  waterIconButtonText: {
    fontSize: 24,
  },
  cardMainNumber: {
    fontSize: 72,
    fontWeight: '800',
    color: '#000',
    marginVertical: 8,
    lineHeight: 80,
  },
  cardMainLabel: {
    fontSize: 14,
    color: '#999',
    fontWeight: '500',
    marginBottom: 24,
  },
  metricItem: {
    alignItems: 'center',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#5C51F0',
    borderRadius: 2,
  },
  waterButtonsContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: 12,
  },
  waterButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
  },
  waterButtonText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '600',
  },
});